---
- hosts: all
  remote_user: ubuntu
  become: yes

  vars:
    proxy_pass: "http://localhost:4000"

  tasks:
    - name: Install Nginx
      apt:
        update_cache: yes
        state: latest
        name: nginx

    - name: Add nginx Config
      ansible.builtin.template:
        src: nginx.conf
        dest: /etc/nginx/sites-available/test.conf

    - name: Criar link simbólico para sites-enabled
      file:
        src: /etc/nginx/sites-available/test.conf
        dest: /etc/nginx/sites-enabled/default
        state: link

    - name: Restart nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes