---
- hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Clone Project
      ansible.builtin.git:
        repo: https://github.com/SrWalkerB/terraform-test
        dest: /home/ubuntu/projects/
    - name: Start Project
      shell: | 
        cd projects && npm start
      args:
        executable: /bin/bash