---
- hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Clone Project
      ansible.builtin.git:
        repo: https://github.com/antony-souza/barbershop
        dest: /home/ubuntu/projects/