---
- hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Clone Project
      ansible.builtin.git:
        repo: https://github.com/SrWalkerB/terraform-test
        dest: /home/ubuntu/projects/

    - name: Run Project With Docker Compose
      ansible.builtin.shell: "docker-compose -f /home/ubuntu/projects/backend-test/docker-compose.yml up -d"